spring:
  application:
    name: spring-batch-sample

  datasource:
    driver-class-name: "your database driver class"
    url: "your database connection string"
    username: "your database username"
    password: "your database password"
    hikari:
      maximum-pool-size: 30
      connection-timeout: 5000
      connection-init-sql: select 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      names: "execute batch job names"
    write:
      file-path: "your csv export file path"

logging:
  level:
    root: info